### ISSUE TITLE
Mention that Read & Write aren't in the prelude when talking about Generic blanket impls

### ISSUE THREAD

**Issue by Akeboshiwind** [pretzelhammer/rust-blog#36]
First off, amazing article! Thanks so much for writing it, it looks like a great reference and I've learnt way more than I probabaly need to know 😅.

In the [Read & Write](https://github.com/pretzelhammer/rust-blog/blob/master/posts/tour-of-rusts-standard-library-traits.md#read--write) section you mention the Generic blanket impls. You already mention this in the [Scope](https://github.com/pretzelhammer/rust-blog/blob/master/posts/tour-of-rusts-standard-library-traits.md#scope) section, but I think it's worth reiterating that Read & Write aren't in the prelude so if you want to use these blanket impls you need to bring them into scope. I think it's a common enough gottcha that a lot of people would be thankfull to be reminded.

**Comment by lebensterben** [comment]
It clearly has

```rust
use std::io::Read;
use std::io::Write;
```

in this section.

**Comment by Akeboshiwind** [comment]
Yeah, but people tend to skip over the imports when reading code. It would
be good to mention it in the text.

**Comment by lebensterben** [comment]
> I think it's a common enough gottcha that a lot of people would be thankfull to be reminded.

No thanks. This article is already too long. No need to add redundant information.

**Comment by Akeboshiwind** [comment]
Fair enough 👍
