### ISSUE TITLE
(nit) Update description of example provided to explain the Clone trait.

### ISSUE THREAD

**Issue by sateeshkumarb** [pretzelhammer/rust-blog#45]
In the section on [Clone](https://github.com/pretzelhammer/rust-blog/blob/master/posts/tour-of-rusts-standard-library-traits.md#clone) the description for function _guarantee_length_ is as below:

> Clone can also be useful in constructing instances of a type within a generic context. Here's an example from the previous section except using Clone instead of Default:
```
fn guarantee_length<T: Clone>(mut vec: Vec<T>, min_len: usize, fill_with: &T) -> Vec<T> {
```
But this function differs from the example in previous section in the method signature too as this takes an additional param `fill_with`. The signature of the function in section [Default](https://github.com/pretzelhammer/rust-blog/blob/master/posts/tour-of-rusts-standard-library-traits.md#default) is as below:
```
fn guarantee_length<T: Default>(mut vec: Vec<T>, min_len: usize) -> Vec<T> {
```

Given this difference, I think the description for function _gurantee_length_ in section _Clone_ can be updated, as it differs from the previous example by taking an additional param. One way I can think of is:
> Clone can also be useful in constructing instances of a type within a generic context. Here's the modified example from the previous section which makes use of Clone instead of Default:

P.S: Thank you for your excellent guides which provide a lucid explanation of many of the Rust concepts.

**Comment by pretzelhammer** [comment]
https://github.com/pretzelhammer/rust-blog/commit/0f257e3131e689349c4de56dc4b1ad1664e49def
