### ISSUE TITLE
Not PostgreSQL but PostgresQL on purpose?

### ISSUE THREAD

**Issue by skanfd** [pretzelhammer/rust-blog#46]
Should I remain this in translation?

**Comment by pretzelhammer** [comment]
Oh, I wasn't aware they re-stylized it. I could have sworn it use to be PostgresQL. Anyway, thanks for asking! I've updated the blog post to change the styling of the text: https://github.com/pretzelhammer/rust-blog/commit/b1cfecc20ed682a4d734fc6ca5711afb4539ec3e
