### ISSUE TITLE
Make a release for each new blog post

### ISSUE THREAD

**Issue by garyng** [pretzelhammer/rust-blog#5]
I enjoy reading your posts!
Maybe make a release after each post is published so that we can subscribe to it? 

Thanks!

**Comment by pretzelhammer** [comment]
Oh cool, that idea never occurred to me, thanks for the suggestion! I'll try it for the next blog post.

**Comment by fmeyer** [comment]
I second this, specially because github generates a RSS feed for releases and tags.

**Comment by pretzelhammer** [comment]
I've started [making releases](https://github.com/pretzelhammer/rust-blog/releases) for every new blog post, including the latest one: [Sizedness in Rust](https://github.com/pretzelhammer/rust-blog/blob/master/posts/sizedness-in-rust.md). Thank you for your feedback! I'm closing this issue as it's complete.
