### ISSUE TITLE
Misconception discussion: T is a superset of both &T and &mut T

### ISSUE THREAD

**Issue by wodny** [pretzelhammer/rust-blog#60]
While it's true and can be presented with generics, maybe a note that the following is possible would be beneficial, so nobody erroneously extrapolates the rule:
```rust
struct Foo();
trait Trait {}
impl Trait for Foo {}
impl Trait for &Foo {}
impl Trait for &mut Foo {}
```
Like with `impl Read for TcpStream` and `impl Read for &TcpStream`.

**Comment by pretzelhammer** [comment]
https://github.com/pretzelhammer/rust-blog/commit/beab8bae9922f9db7aad0611cb5973d12db718eb
