### ISSUE TITLE
More iteration trait wisdom

### ISSUE THREAD

**Issue by HadrienG2** [pretzelhammer/rust-blog#68]
Here are a few extra things I wish I knew when I started messing with Rust's iteration traits, in addition to what your tour of Rust traits already contains:

- `Iterator` is one of those few traits where you should _really_ consider overloading the default implementation of some methods (size_hint, nth...), as it is suboptimal in many cases.
- `Extend` is a thing and `FromIterator` should almost always be implemented in terms of it.

**Comment by pretzelhammer** [comment]
thanks for the feedback, article updated: https://github.com/pretzelhammer/rust-blog/commit/b64a03c595c306a526da83aa4c4a143d4ee8bf57
