### ISSUE TITLE
rss reeder?

### ISSUE THREAD

**Issue by hhamud** [pretzelhammer/rust-blog#88]
anyway of converting this into a full blown website with rss included?

**Comment by lebensterben** [comment]
just watch this repo

**Comment by pretzelhammer** [comment]
Similar issue from a few years back: https://github.com/pretzelhammer/rust-blog/issues/5

I publish a "github release" for every blog post, and github generates an RSS feed for releases which you can subscribe to. When browsing the repo you can also click on "Watch" -> "Custom" -> "Releases" in the top-right of the github UI (by the "Fork" and "Star" buttons) to get notifications through github when I publish a new blog post.

I hope that helps! If it doesn't feel free to re-open this issue to continue the discussion, thanks.

**Comment by hhamud** [comment]
I had no idea thanks. It took some additional googling to find out the exact link for the feed is this: https://github.com/pretzelhammer/rust-blog/releases.atom
